# Generated by Django 3.1.5 on 2021-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0006_profile_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
