# Generated by Django 3.1.5 on 2021-04-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0008_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
