# Generated by Django 3.1.5 on 2021-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0012_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
