# Generated by Django 3.1.5 on 2021-04-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0014_feedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
