# Generated by Django 3.1.5 on 2021-04-14 05:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yapp', '0015_feedbackmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='complaint',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
